spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/login_test?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
server:
  servlet:
    context-path: /
